const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const versionJsonPath = path.join(rootDir, 'version.json');
const versionJsPath = path.join(rootDir, 'version.js');
const assetsVersionJsPath = path.join(rootDir, 'assets', 'version.js');
const packageJsonPath = path.join(rootDir, 'package.json');

// 1. Determine Git metadata if available
let commitCount = 68;
let commitHash = 'b7396fb';
let hasGit = false;

try {
  const countStr = execSync('git rev-list --count HEAD', { cwd: rootDir, encoding: 'utf8' }).trim();
  const hashStr = execSync('git rev-parse --short HEAD', { cwd: rootDir, encoding: 'utf8' }).trim();
  if (countStr && !isNaN(parseInt(countStr, 10))) {
    commitCount = parseInt(countStr, 10);
    commitHash = hashStr;
    hasGit = true;
  }
} catch (e) {
  // Fallback to reading existing version.json
}

// 2. Read or initialize version.json
let currentData = {
  major: 2,
  minor: 4,
  patch: commitCount,
  version: `2.4.${commitCount}`,
  channel: 'production'
};

if (fs.existsSync(versionJsonPath)) {
  try {
    currentData = JSON.parse(fs.readFileSync(versionJsonPath, 'utf8'));
  } catch (err) {
    console.warn('Could not parse version.json, creating anew.');
  }
}

const major = currentData.major || 2;
const minor = currentData.minor || 4;

// If in git, patch is sync'd to commit count; otherwise increment
let patch = hasGit ? commitCount : (parseInt(currentData.patch || 0, 10) + 1);

const fullVersion = `${major}.${minor}.${patch}`;
const now = new Date();
const dateStr = now.toISOString().split('T')[0];

const updatedVersionData = {
  version: fullVersion,
  major: major,
  minor: minor,
  patch: patch,
  commit: commitHash,
  commitCount: commitCount,
  releaseName: 'Bharat Retail Intelligence',
  updatedAt: now.toISOString(),
  releaseDate: dateStr,
  channel: currentData.channel || 'production'
};

// 3. Save version.json
fs.writeFileSync(versionJsonPath, JSON.stringify(updatedVersionData, null, 2) + '\n', 'utf8');

// 4. Generate version.js content
const versionJsContent = `/**
 * PriyuLabs Universal Dynamic Version Manager
 * Auto-generated by scripts/auto-version.cjs
 */
(function () {
  'use strict';

  var VERSION_INFO = ${JSON.stringify(updatedVersionData, null, 2)};

  window.PRIYULABS_VERSION = 'v' + VERSION_INFO.version;
  window.PRIYULABS_VERSION_INFO = VERSION_INFO;

  function ensureVersionStyles() {
    if (document.getElementById('priyulabs-version-styles')) return;
    var style = document.createElement('style');
    style.id = 'priyulabs-version-styles';
    style.textContent = \`
      .foot-version-badge {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 0.03em;
        color: var(--ink-soft, #6B6152);
        background: rgba(0, 0, 0, 0.035);
        border: 1px solid var(--line, #E3D9C1);
        padding: 3px 9px;
        border-radius: 999px;
        text-decoration: none;
        transition: all 0.2s ease;
        line-height: 1;
        vertical-align: middle;
        user-select: none;
      }
      [data-theme="dark"] .foot-version-badge {
        background: rgba(255, 255, 255, 0.06);
        border-color: rgba(255, 255, 255, 0.12);
        color: #94a3b8;
      }
      .foot-version-badge:hover {
        background: var(--accent-soft, #E7EEE4);
        color: var(--accent, #3F5D42);
        border-color: var(--accent, #3F5D42);
        transform: translateY(-1px);
      }
      .version-pulse-dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        background-color: #22c55e;
        display: inline-block;
        box-shadow: 0 0 0 0 rgba(34, 197, 94, 0.7);
        animation: priyulabsVersionPulse 2.4s infinite cubic-bezier(0.66, 0, 0, 1);
      }
      @keyframes priyulabsVersionPulse {
        0% { box-shadow: 0 0 0 0 rgba(34, 197, 94, 0.7); }
        70% { box-shadow: 0 0 0 6px rgba(34, 197, 94, 0); }
        100% { box-shadow: 0 0 0 0 rgba(34, 197, 94, 0); }
      }
    \`;
    document.head.appendChild(style);
  }

  function renderVersion() {
    ensureVersionStyles();

    var displayStr = 'v' + VERSION_INFO.version;

    var existingVersionEls = document.querySelectorAll('.foot-version, #siteVersion, [data-site-version]');
    if (existingVersionEls.length > 0) {
      existingVersionEls.forEach(function (el) {
        el.textContent = displayStr;
      });
    }

    var footBottoms = document.querySelectorAll('.foot-bottom, footer .bottom-bar, footer .copyright-wrap');
    footBottoms.forEach(function (footBottom) {
      if (footBottom.querySelector('.foot-version-badge')) return;

      var badge = document.createElement('span');
      badge.className = 'foot-version-badge';
      badge.title = 'PriyuLabs Platform ' + displayStr + ' (' + VERSION_INFO.releaseDate + ')';
      badge.innerHTML = '<span class="version-pulse-dot"></span><span class="foot-version">' + displayStr + '</span>';

      if (footBottom.children.length >= 2) {
        footBottom.insertBefore(badge, footBottom.children[1]);
      } else {
        footBottom.appendChild(badge);
      }
    });
  }

  // Cleanup any lingering page loader elements
  function cleanupLingeringLoaders() {
    var el = document.getElementById('priyulabsGlobalPageLoader');
    if (el) {
      try { el.remove(); } catch (e) { el.style.display = 'none'; }
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () {
      renderVersion();
      cleanupLingeringLoaders();
    });
  } else {
    renderVersion();
    cleanupLingeringLoaders();
  }
})();
`;

fs.writeFileSync(versionJsPath, versionJsContent, 'utf8');
if (fs.existsSync(path.dirname(assetsVersionJsPath))) {
  fs.writeFileSync(assetsVersionJsPath, versionJsContent, 'utf8');
}
const webPublicVersionJs = path.join(rootDir, 'apps', 'web', 'public', 'version.js');
if (fs.existsSync(path.dirname(webPublicVersionJs))) {
  fs.writeFileSync(webPublicVersionJs, versionJsContent, 'utf8');
}

// 5. Update package.json
if (fs.existsSync(packageJsonPath)) {
  try {
    const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    pkg.version = fullVersion;
    fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
  } catch (e) {}
}

// 6. Synchronize version in static HTML files
let updatedHtmlCount = 0;

function updateHtmlFiles(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (['node_modules', '.git', 'brain', 'apps'].includes(entry.name)) continue;
      updateHtmlFiles(fullPath);
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      let html = fs.readFileSync(fullPath, 'utf8');
      let changed = false;

      // 1. If foot-version already exists, update version string
      const badgeRegex = /<span\b[^>]*class="[^"]*\bfoot-version\b[^"]*"[^>]*>[^<]*<\/span>/gi;
      if (badgeRegex.test(html)) {
        html = html.replace(badgeRegex, `<span class="foot-version" id="siteVersion">v${fullVersion}</span>`);
        changed = true;
      } else {
        // 2. If foot-bottom exists without badge, inject badge
        const footBottomRegex = /(<div\b[^>]*class="[^"]*\bfoot-bottom\b[^"]*"[^>]*>[\s\S]*?<span>(?:&copy;|©)[^<]*<\/span>)([\s\S]*?)(<span>(?:MSME|UDYAM)[^<]*<\/span>)/i;
        if (footBottomRegex.test(html)) {
          const badgeHtml = `\n        <span class="foot-version-badge" title="PriyuLabs Platform v${fullVersion} (Live)"><span class="version-pulse-dot"></span><span class="foot-version" id="siteVersion">v${fullVersion}</span></span>`;
          html = html.replace(footBottomRegex, `$1${badgeHtml}\n        $3`);
          changed = true;
        }
      }

      // 3. Ensure version.js is included before </body>
      if (!html.includes('version.js') && html.includes('</body>')) {
        const relPath = path.relative(path.dirname(fullPath), rootDir).replace(/\\/g, '/');
        const scriptSrc = relPath ? `${relPath}/version.js` : 'version.js';
        html = html.replace('</body>', `  <script src="${scriptSrc}"></script>\n</body>`);
        changed = true;
      }

      if (changed) {
        fs.writeFileSync(fullPath, html, 'utf8');
        updatedHtmlCount++;
      }
    }
  }
}

try {
  updateHtmlFiles(rootDir);
} catch (e) {
  console.warn('HTML update warning:', e.message);
}

console.log(`[PriyuLabs Auto-Version] Synchronized to v${fullVersion} (Commits: ${commitCount}, Hash: ${commitHash}, HTML Files Updated: ${updatedHtmlCount})`);
